server:
  port: 8100

spring:
  application:
    name: config-server-mcs-app
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/
